### ISSUE TITLE
IOS <10.2 报错

### ISSUE THREAD

**Issue by heke2929** [zdliuccit/ml-ui#10]
TypeError: Object.values is not a function. (In 'Object.values(e)', 'Object.values' is undefined)
(匿名函数) -- ml-ui.js:1:5871
use -- vue.esm.js:4681
NHnr -- main.js:37
n -- bootstrap d3a93ad4bd3c6ae2ab7a:54
webpackJsonp -- bootstrap d3a93ad4bd3c6ae2ab7a:25
全局代码 -- app.1c3ac8f5c5638b1985b8.js:1

**Comment by zdliuccit** [comment]
@heke2929 
已修复。
主要是es6、es7 的高级语法，
1、需要全局引入 babel-polyfill
2、或者，引入额外的库 import assign from 'object-assign';
....还有其他方法，
这个工程配置过了，忘了npm包的了。
