### ISSUE TITLE
i-view组件

### ISSUE THREAD

**Issue by yogurtWang** [zdliuccit/ml-ui#14]
i-view组件好像不适用于多张图片用同一个组件。如果复用同一个组件然后改变url好像width仍然会沿用上一次的width。

**Comment by zdliuccit** [comment]
@yogurtWang 你那边什么场景，我测试了 不会的啊

**Comment by yogurtWang** [comment]
就普通的使用场景，点击小图把该图的url传入组件，查看大图的预览而已。
