### ISSUE TITLE
Do not use built-in or reserved HTML elements as component id: button

### ISSUE THREAD

**Issue by medz** [zdliuccit/ml-ui#2]
You should avoid using the native html name as the component name.

**Comment by zdliuccit** [comment]
Thanks, the later improvement

**Comment by zdliuccit** [comment]
Thank you very much. The original setting was like this. There was too much to be considered in the later period. Now I think it's better to change it back.

**Comment by medz** [comment]
@zdliuccit Ah! I think when your project has a name, this context should be used in the `name` field. The latter hope to change to a just name, you can use the method of volume replacement, the workload also in five minutes.

**Comment by zdliuccit** [comment]
This does not consider, after all, the name of the start of the project will not be changed.

**Comment by zdliuccit** [comment]
@medz This does not consider, after all, the name of the start of the project will not be changed.
