### ISSUE TITLE
您好，请问px和rem的适配

### ISSUE THREAD

**Issue by Yaob1990** [zdliuccit/ml-ui#21]
在阅读源码时候，看到有一次commit 是rem 改成px

请问，为什么要这样改呢。

现在使用的化，是不是要用postcss再把px 转成rem？

也想写个组件库，在这里有点纠结，求指点

**Comment by zdliuccit** [comment]
组件库的化相对来说不是太需要rem，只要px就行

**Comment by Yaob1990** [comment]
感谢
